name: JP2048
main: ch.thejp.plugin.game2048.JP2048Plugin
version: 1.0.1
commands:
  2048:
    description: Open game
    usage: /<command>
    permission: thejp.2048.play
    permission-message: Permission <permission> is needed
  2048 new:
    description: Start new game
    usage: /<command>
    permission: thejp.2048.play
    permission-message: Permission <permission> is needed
  2048 stats:
    description: Show stored highscores
    usage: /<command>
    permission: thejp.2048.play
    permission-message: Permission <permission> is needed
permissions:
  thejp.2048.*:
    description: Contains every 2048 permission
    default: op
    children:
      thejp.2048.play: true
  thejp.2048.play:
    descripten: Permits to play 2048
    default: true
